#######################################
# LOCALE E ENCODING
#######################################
spring.web.locale-resolver=fixed
spring.web.locale=pt_BR

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true

#######################################
#  BANCO DE DADOS - POSTGRESQL
#######################################
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/dscatalog
spring.datasource.username=${POSTGRES_DATASOURCE_USER}
spring.datasource.password=${POSTGRES_DATASOURCE_PASSWORD}

#######################################
#  JPA / HIBERNATE
#######################################

#  IMPORTANTE: quando usa Flyway, NÃO usar update/create
spring.jpa.hibernate.ddl-auto=none

# Mostrar SQL no console (útil em DEV)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#######################################
#  FLYWAY (MIGRATIONS)
#######################################
spring.flyway.enabled=true

# Locais separados (SCHEMA e DATA)
spring.flyway.locations=classpath:db/migration/schema,classpath:db/migration/data

logging.level.org.flywaydb=DEBUG

#######################################
#  LOGGING
#######################################

# Nível global (menos poluído)
logging.level.root=WARN

# Logs da aplicação (seu pacote)
logging.level.com.albertsilva.dev.dscatalog=DEBUG

# Logs do Spring Framework
logging.level.org.springframework=INFO

# SQL gerado pelo Hibernate
logging.level.org.hibernate.SQL=DEBUG

# Valores dos parâmetros SQL (muito útil em DEV)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#######################################
#  LOG EM ARQUIVO
#######################################
logging.file.name=logs/dev/dscatalog-dev.log

# Rotação de logs
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=10