# Nível de Log para Produção (ajustado para INFO/WARN para reduzir o volume de logs em produção)
logging.level.root=WARN
logging.level.com.albertsilva.dev.dscatalog=INFO
logging.level.org.springframework.web=WARN

# SQL desligado (performance)
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF

# Arquivo
logging.file.name=logs/dscatalog-prod.log

# Rolling
logging.logback.rollingpolicy.max-file-size=50MB
logging.logback.rollingpolicy.max-history=30